package modelo;

public enum Eventos {
	PUEDE_EMPEZAR_JUEGO,
	NO_ENTRAN_MAS_JUGADORES,
	JUGADOR_AGREGADO,
	JUEGO_TERMINADO,
	SEGUIR_JUEGO, 
	CAMBIO_TURNO,
	MANO_TERMINADA,
	RAYA,
	MANO_TERMINADA_Y_RAYA
}
