package modelo;


public enum Eventos {
	PUEDE_EMPEZAR_JUEGO, NO_ENTRAN_MAS_JUGADORES, JUGADOR_AGREGADO,REPARTIDO,INTERMEDIO_GANADO,INTERMEDIO_PERDIDO,JUEGO_TERMINADO,MANO_TERMINADA, DINERO_INGRESADO
	
}
