package Modelo;

public enum EstadoJuego {
	JUGADOR_AGREGADO, 
	JUGADOR_AGREGADO_PUEDE_EMPEZAR,
	CARTAS_REPARTIDAS,
	CARTA_ROBADA,
	CARTA_TIRADA_DESCATADA_PUESTA_OTRA_CARTA, 
	CARTAS_TIRADAS_JUGADOR_PONER_CARTA,
	JUEGO_TERMINADO;
}
